package com.routefill.entity;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "road_consignments")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class RoadConsignment {
    @Id
    @Column(length = 64)
    private String id; // RF-2026-XXXXXX

    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "booking_id", nullable = false, unique = true)
    private BookingRequest booking;

    @Column(nullable = false, length = 255)
    @Builder.Default
    private String disclaimer = "Digital Road Logistics Record generated by ROUTEFILL. This does not replace legally required government transport documents.";

    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    @PrePersist
    protected void onCreate() {
        if (createdAt == null) createdAt = LocalDateTime.now();
    }
}
